### ISSUE TITLE
Possible to have double links from one node to another node

### ISSUE THREAD

**Issue by yubrshen** [theodorewiles/org-mind-map#3] opened 2017-08-10 19:20 UTC
Very impressive start!

I just concated the examples in README into one file, I found that there are double links from some nodes to some others. It seems a bug. 

Attached are the related files:

[double-link-problem.zip](https://github.com/theodorewiles/org-mind-map/files/1216084/double-link-problem.zip)

**Comment by academikuser** [comment] 2017-08-10 19:49
Do you mean the feature in  ./org-mind-map/example-3.org.png
where two trees merge?

**Comment by the-ted** [comment] 2017-08-10 20:08
I believe that's a feature, not a bug! As described, if your headings are named the same they will be merged.

**Closed as completed by the-ted** 2017-08-10 20:08 UTC

**Comment by yubrshen** [comment] 2017-08-10 23:38
Please take a look at the PDF in the attached zip file. Even with merge, it
should not be possible to two links between the same pair of nodes. In the
attached example, there are such cases.

**Comment by the-ted** [comment] 2017-08-11 01:11
Nodes with identical headings are combined, but paths aren't. I think we can leave it this way. If you want to get rid of having two links between the same pair of nodes, then you should merge the headings in the source org file.
